name: wt_map_menu
description: The wt_map_menu is for...
version: 1.0.0+1
publish_to: 'none' # To publish to pub.dev, remove this line
homepage: https://github.com/tmcmaster/wt_map_menu

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: flutter analyze
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  coverage:
    generate: ./bin/generate_coverage.sh
    view: open coverage/html/index.html

dependencies:
  csv: ^5.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  wt_firepod:
    git:
      url: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git:
      url: https://github.com/tmcmaster/wt_models.git

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  json_annotation: "^4.8.1"
  json_serializable: